# refer to https://mpv.io/manual/stable/ for configuration reference
# mpv keybindings

# Cycle between sub files
c cycle sub
C cycle sub down

# Navigate through playlist files
> playlist-next
< playlist-prev