#-----Screenshots-----
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-directory="~/media/pic/screenshot/mpv/"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"