#-----Screenshots-----
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-directory="~/media/pic/screenshot/mpv/"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

#-----Subtitles-----
# Automatically use the subtitle file that has approximately the same name as the video file
sub-auto=fuzzy
subs-with-matching-audio=yes

