unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf\; display "Reloaded!"

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -g status-position top

# set $TERM for compatibility
set -g default-terminal "screen-256color"

set -g @ukiyo-plugins "time"
set -g @ukiyo-time-format "%a %Y-%m-%d %H:%M %Z"
set -g @ukiyo-show-powerline true
set -g @ukiyo-theme "kanagawa/dragon"
set -g @ukiyo-ignore-window-colors true

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

run '~/.local/share/tmux/plugins/tpm/tpm'
