# change prefix key to ctrl+space
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# bind r to re-source tmux.conf
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf\; display "Reloaded!"

# mouse support
set -g mouse on

# window indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# vim keybindings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-key -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# M -> shift+alt+[]
bind -n M-H previous-window
bind -n M-L next-window

# open panes in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# status bar on top
set-option -g status-position top

# color range
set-option -sa terminal-overrides ",xterm*:Tc"

# kanagawa options
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-theme 'dragon'
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, 
# network-bandwidth, network-ping, ssh-session, attached-clients, network-vpn, weather, time,
# mpc, spotify-tui, playerctl, kubernetes-context, synchronize-panes
set -g @kanagawa-plugins "time"
set -g @kanagawa-show-powerline true
set -g @kanagawa-time-format "%a %Y-%m-%d %H:%M %Z"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Nybkox/tmux-kanagawa'
# set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.config/tmux/plugins/tpm/tpm'
