# change prefix key to ctrl+space
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# bind r to re-source tmux.conf
unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf\; display "Reloaded!"

# mouse support
set -g mouse on

# window indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# open panes in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# status bar on top
set-option -g status-position top

# set $TERM
set -g default-terminal "screen-256color"

# || Ukiyo options||
# load plugins
set -g @ukiyo-plugins "time"
# set the time format
set -g @ukiyo-time-format "%a %Y-%m-%d %H:%M %Z"
# enable powerline symbols
set -g @ukiyo-show-powerline true
# set the theme
set -g @ukiyo-theme "kanagawa/dragon"
# disable theme colours for terminal window
set -g @ukiyo-ignore-window-colors true

# List of plugins to load
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.local/share/tmux/plugins/tpm/tpm'
